version: '3'

services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
      - data:/var/lib/postgresql/data

volumes:
  data: